apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: mattermost
  labels:
    app: postgres
data:
  POSTGRES_DB: mattermost
  POSTGRES_USER: mattermost
  POSTGRES_PASSWORD: chocolateFrog!