apiVersion: v1
stringData: # use stringData instead of data to avoid base64 encoding
  # PostgreSQL connection string
  # Format: postgresql://[user[:password]@][host][:port][/dbname][?param1=value1&param2=value2]
  DB_CONNECTION_STRING: "postgres://mattermost:chocolateFrog!@postgres.mattermost.svc.cluster.local:5432/mattermost?sslmode=disable&connect_timeout=10"
  DB_CONNECTION_CHECK_URL: "postgres://mattermost:chocolateFrog!@postgres.mattermost.svc.cluster.local:5432/mattermost?sslmode=disable&connect_timeout=10"

  # This add a read only replic. Deployment needs to be done separately
  # MM_SQLSETTINGS_DATASOURCEREPLICAS: "postgres://mmuser:chocolateFrog!@postgres-replica.mattermost.svc.cluster.local:5432/mattermost?connect_timeout=10"

kind: Secret
metadata:
  name: mattermost-postgres-connection
  namespace: mattermost
type: Opaque
