apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mattermost-filestore-pvc
  namespace: mattermost
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 20Gi
