apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mm-plugins
spec:
  capacity:
    storage: 1Gi
  accessModes: ["ReadWriteOnce"]
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: storage
          operator: In
          values: ["mattermost"]
  hostPath:
    path: /mnt/mattermost/plugins
